### ISSUE TITLE
Actuator info not Hystrix info

### ISSUE THREAD

**Issue by HeCG95** [itmuch/spring-cloud-docker-microservice-book-code#12]
hello, when i tested on chapter7 about hystrix:
i accessed http://localhost:8010/health, the only info as follows:
```json
{"description":"Composite Discovery Client","status":"UP"}
```
as if there was not Hystrix info.
Could you give me some advice? i run ```microservice-consumer-movie-ribbon-hystrix```
It seemd like ```HystrixHealthIndicator``` didn't work.

**Comment by xn-9527** [comment]
You need to add config to avoid security forbbiden for displaying details.It was mentioned in former chapter.

```
management:
  security:
    enabled: false
```
