### ISSUE TITLE
microservice-consumer-movie-feign-manual

### ISSUE THREAD

**Issue by pzs-pzs** [itmuch/spring-cloud-docker-microservice-book-code#5]
你好，我在学习microservice-consumer-movie-feign-manual手动配置feign时，本地按照你的代码写demo时候发现无法自动装配Decoder、Encoder、Client、Contract

**Comment by eacdy** [comment]
您好，貌似已经QQ私聊解决了哈。建议将解决的方案贴出来，方便其他的读者兄弟们。

**Comment by pzs-pzs** [comment]
- 已经解决了，不是无法注入的原因

 - 解决方法：
      springcloud中默认feign配置类FeignClientsConfiguration中的contract是SpringMvcContract而我是置feignClient接口时使用了feign原生注解@RequestLine，这个注解不是springmvc注解所以出现了bug，将其换成@RequestMapping即可解决这个问题

**Comment by eacdy** [comment]
赞
