### ISSUE TITLE
feign 怎么配置像ribbon一样可以选择调度策略呢

### ISSUE THREAD

**Issue by ghost** [itmuch/spring-cloud-docker-microservice-book-code#9]
ribbon 调度服务的策略有 轮寻  随机等等策略 Feign既然集成了ribbon但是它的默认配置是轮寻 我想改成随机或其他的 怎么配置呀

**Comment by eacdy** [comment]
ribbon怎么配，用feign的时候依然怎么配置。

**Comment by ghost** [comment]
我在microservice-consumer-movie-feign 消费者的application.yml  加了一段这个 
ribbon: 
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule 但是试了还是轮询

**Comment by eacdy** [comment]
@mrsWangxing 版本是？

**Comment by ghost** [comment]
我的代码就是从 这个仓库里面 直接fork到我的github中的 然后导入到我的eclipse中的

**Comment by ghost** [comment]
我刚才试了下 ribbon的 这样的配置不起作用
ribbon: 
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
这样的可以
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
不知道为什么

**Comment by ghost** [comment]
刚确认了下  我这里 不管是ribbon(microservice-consumer-movie-ribbon)还是fiegn(microservice-consumer-movie-feign)项目  配置全局的策略 都不行 必须加上服务提供者的名字类似 microservice-provider-user

**Comment by eacdy** [comment]
@mrsWangxing 哦哦，升级到edgware sr1以及更新版本吧。我仓库用的是edgware.release，这个版本bug比较多。

**Comment by ghost** [comment]
哈哈  知道原因了就行了 学习 就先用这个版本吧
